language: go
arch:
    - amd64
    - ppc64le
go:
 - 1.9.x
 - 1.10.x
 - 1.11.x
 - 1.12.x
 - 1.13.x
 - 1.14.x
 - tip
 
matrix:
     allow_failures:
     - go: tip
     - go: 1.9.x
     - go: 1.10.x
     - go: 1.11.x
     - go: 1.12.x 

dist: bionic
addons:
  apt:
    packages:
    - bison
    - flex
    - automake
    - autoconf
    - libtool
    - make
    - gcc
    - pkg-config
before_install:
  - wget --no-verbose -O- https://github.com/VirusTotal/yara/archive/v4.0.1.tar.gz | tar -C ${HOME} -xzf -
  - ( cd ${HOME}/yara-4.0.1 && ./bootstrap.sh )
  - ( mkdir -p ${HOME}/yara-build &&
      cd ${HOME}/yara-build &&
      ${HOME}/yara-4.0.1/configure --prefix=${HOME}/prefix )
  - make -C ${HOME}/yara-build install
  - find ${HOME}/prefix
  - export PKG_CONFIG_PATH=${HOME}/prefix/lib/pkgconfig
  - export LD_LIBRARY_PATH=${HOME}/prefix/lib
